### ISSUE TITLE
one-time manual bulk message ingestion

### ISSUE THREAD

**Issue by christo4b** [hrx/slack-private-archiver#5]
- [ ] export all messages from slack
- [ ] massage messages into format for db ingestion
- [ ] load messages into db

We can use the export feature from slack to export all of the messages 

Here are some resources regarding export functionality:
https://levels.io/slack-export-to-html/
https://gist.github.com/levelsio/122907e95956602e5c09
https://github.com/hfaran/slack-export-viewer
https://gist.github.com/Chandler/fb7a070f52883849de35
https://get.slack.help/hc/en-us/articles/201658943-Export-your-team-s-Slack-history

**Comment by mi-lee** [comment]
Looks like SlackArchive (the techcrunch link) is free, should we give it a try?

**Comment by aeb0** [comment]
@dting proposed using [this tool](https://github.com/bsvingen/slack2pg) for either or both of 1) loading the initial export into postgres and 2) writing new messages into postgres as they occur.  If we can get it to work it would be pretty sweet.

The clojure code is throwing an error for me though. Here is the config.edn file I was using:
```{
 ;; PostgreSQL credentials
 :db-host "ec2-52-9-62-85.us-west-1.compute.amazonaws.com"
 :db-port 5432
 :db-name slack
 :db-user slack
 :db-password slack

 ;; Slack team info - team-id only required for reading export files
 :team "hrx"
 :team-id "T035Z8YSZ"}
```

@mLuby @cehsu

**Comment by aeb0** [comment]
Stack trace from `slack2pg` error

```target/slack2pg config.edn read-export ~/Downloads/HRX\ Slack\ export\ Nov\ 9\ 2016.zip
WARNING: bounded-count already refers to: #'clojure.core/bounded-count in namespace: clojure.core.async, being replaced by: #'clojure.core.async/bounded-count
Exception in thread "main" java.lang.AssertionError: Assert failed: (every? valid-entry? entries)
	at com.borkdal.slack2pg.db$write_to_temp_table.invokeStatic(db.clj:335)
	at com.borkdal.slack2pg.db$write_to_temp_table.invoke(db.clj:335)
	at com.borkdal.slack2pg.db$write_batch_to_db$fn__15538.invoke(db.clj:355)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:584)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:557)
	at clojure.lang.RestFn.invoke(RestFn.java:521)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:600)
	at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:557)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at com.borkdal.slack2pg.db$write_batch_to_db.invokeStatic(db.clj:353)
	at com.borkdal.slack2pg.db$write_batch_to_db.invoke(db.clj:351)
	at com.borkdal.slack2pg.export$write_export_messages_to_database.invokeStatic(export.clj:165)
	at com.borkdal.slack2pg.export$write_export_messages_to_database.invoke(export.clj:160)
	at com.borkdal.slack2pg$_main.invokeStatic(slack2pg.clj:41)
	at com.borkdal.slack2pg$_main.doInvoke(slack2pg.clj:24)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at com.borkdal.slack2pg.main(Unknown Source)
```

**Comment by mLuby** [comment]
Closing as old.
